### ISSUE TITLE
Sample sheet not recognizing sample type 'mpx'

### ISSUE THREAD

**Issue by cpfeifer58** [MaWeffm/ReCo#1]
I have copied the sample sheet, updating with my own paths, and am attempting to run Reco but am running into an error:

```
2023-08-28 11:19:18 INFO: Unique samples: ['pgEX']
2023-08-28 11:19:18 WARNING: {'valid': False, 'message': 'Unknown sample type!'}
2023-08-28 11:19:18 INFO: Running on 1 cores
2023-08-28 11:19:18 INFO: Remove intermediate files: True
2023-08-28 11:19:18 INFO: Found 0 valid samples: []
```

After which it stops running. I'm attaching the sample sheet as is, with sample paths. Are there other sample type options besides single and mpx? Is it a problem with xlsx format? 

Thanks in advance, please let me know if I can include anything else!

[ghub_sample_sheet.xlsx](https://github.com/MaWeffm/ReCo/files/12457722/ghub_sample_sheet.xlsx)

**Comment by MaWeffm** [comment]
Thank you @cpfeifer58!
Please use the sample type 'paired' instead of 'mpx' and let my know if it works. I updated the documentation accordingly.

**Comment by cpfeifer58** [comment]
Thanks @MaWeffm! I really appreciate the quick response and it worked!

Unfortunately I've run into another issue but I'll open a new post with that.
